export const CREATE_USER = "CREATE_USER";
export const GET_USER_BY_ID = "GET_USER_BY_ID";
export const LOAD_USER_DATA = "LOAD_USER_DATA";

export const SET_ALERT = "SET_ALERT";
export const SHOW_CIRCULAR_BTN = "SHOW_CIRCULAR_BTN";
export const SET_THEME = "SET_THEME";

export const SET_SELECTED_SLOT_SESSION = "SET_SELECTED_SLOT_SESSION";

export const SET_FILTER_TURF_SIZE = "SET_FILTER_TURF_SIZE";
export const SET_FILTER_PRICE = "SET_FILTER_PRICE";
export const SET_FILTER_SLOTS = "SET_FILTER_SLOTS";
export const SET_FILTER_START_TIME = "SET_FILTER_START_TIME";
export const SET_FILTER_END_TIME = "SET_FILTER_END_TIME";

export const SET_SELECTED_TURF_SIZE = "SET_SELECTED_TURF_SIZE";
export const SET_SELECTED_PRICE = "SET_SELECTED_PRICE";
export const SET_SELECTED_START_TIME = "SET_SELECTED_START_TIME";
export const SET_SELECTED_END_TIME = "SET_SELECTED_END_TIME";
